=== Rahwulkumar/XML_WEB_4-5/LAB4/forexTrades.dtd
<!ELEMENT forexTrades (trade+)>
<!ELEMENT trade (tradeID, currencyPair, tradeDate, units, price, tradeType)>
<!ELEMENT tradeID (#PCDATA)>
<!ELEMENT currencyPair (#PCDATA)>
<!ELEMENT tradeDate (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT tradeType (#PCDATA)>

=== Rahwulkumar/XML_WEB_4-5/LAB4/forexTrades.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!DOCTYPE forexTrades SYSTEM "forexTrades.dtd">
<forexTrades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="forexTrades.xsd">
    <trade>
        <tradeID>F001</tradeID>
        <currencyPair>EUR/USD</currencyPair>
        <tradeDate>2024-08-09</tradeDate>
        <units>1000</units>
        <price>1.1850</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F002</tradeID>
        <currencyPair>GBP/USD</currencyPair>
        <tradeDate>2024-08-09</tradeDate>
        <units>500</units>
        <price>1.3900</price>
        <tradeType>sell</tradeType>
    </trade>
    <trade>
        <tradeID>F003</tradeID>
        <currencyPair>USD/JPY</currencyPair>
        <tradeDate>2024-08-10</tradeDate>
        <units>200</units>
        <price>110.2500</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F004</tradeID>
        <currencyPair>AUD/USD</currencyPair>
        <tradeDate>2024-08-10</tradeDate>
        <units>800</units>
        <price>0.7400</price>
        <tradeType>sell</tradeType>
    </trade>
    <trade>
        <tradeID>F005</tradeID>
        <currencyPair>USD/CAD</currencyPair>
        <tradeDate>2024-08-11</tradeDate>
        <units>300</units>
        <price>1.2550</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F006</tradeID>
        <currencyPair>NZD/USD</currencyPair>
        <tradeDate>2024-08-11</tradeDate>
        <units>1000</units>
        <price>0.7000</price>
        <tradeType>sell</tradeType>
    </trade>
    <trade>
        <tradeID>F007</tradeID>
        <currencyPair>EUR/GBP</currencyPair>
        <tradeDate>2024-08-12</tradeDate>
        <units>400</units>
        <price>0.8560</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F008</tradeID>
        <currencyPair>USD/CHF</currencyPair>
        <tradeDate>2024-08-12</tradeDate>
        <units>250</units>
        <price>0.9200</price>
        <tradeType>sell</tradeType>
    </trade>
    <trade>
        <tradeID>F009</tradeID>
        <currencyPair>EUR/JPY</currencyPair>
        <tradeDate>2024-08-13</tradeDate>
        <units>600</units>
        <price>129.8000</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F010</tradeID>
        <currencyPair>GBP/JPY</currencyPair>
        <tradeDate>2024-08-13</tradeDate>
        <units>450</units>
        <price>152.3000</price>
        <tradeType>sell</tradeType>
    </trade>
    <trade>
        <tradeID>F011</tradeID>
        <currencyPair>AUD/JPY</currencyPair>
        <tradeDate>2024-08-14</tradeDate>
        <units>700</units>
        <price>81.6000</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F012</tradeID>
        <currencyPair>EUR/AUD</currencyPair>
        <tradeDate>2024-08-14</tradeDate>
        <units>350</units>
        <price>1.6000</price>
        <tradeType>sell</tradeType>
    </trade>
    <trade>
        <tradeID>F013</tradeID>
        <currencyPair>CAD/JPY</currencyPair>
        <tradeDate>2024-08-15</tradeDate>
        <units>900</units>
        <price>88.7000</price>
        <tradeType>buy</tradeType>
    </trade>
    <trade>
        <tradeID>F014</tradeID>
        <currencyPair>NZD/JPY</currencyPair>
        <tradeDate>2024-08-15</tradeDate>
        <units>600</units>
        <price>76.4000</price>
        <tradeType>sell</tradeType>
    </trade>
</forexTrades>
